"use client";

import { useState, useEffect } from "react";
import Link from "next/link";
import toast from "react-hot-toast";
import { useAuth } from "@/context/AuthContext";
import type { ApplicableLaw } from "@/lib/services/ai";
import type { UserDetails } from "@/lib/services/complaint";
import { fmtDate } from "@/lib/services/complaint";

// ─── Types ──────────────────────────────────────────────────────────────────
type Tab = "full" | "short";
type GuideTab = "online" | "offline";

// ─── Helpers ─────────────────────────────────────────────────────────────────
const LAW_SEVERITY_STYLE = (act: string): string => {
  if (act.includes("POCSO") || act.includes("Domestic Violence"))
    return "bg-tertiary/20 text-tertiary border border-tertiary/30";
  if (act.includes("67A") || act.includes("67B") || act.includes("354A") || act.includes("506"))
    return "bg-[#ff544a]/10 text-[#ff8a7a] border border-[#ff544a]/20";
  if (act.includes("66E") || act.includes("67") || act.includes("354D") || act.includes("503") || act.includes("507"))
    return "bg-[#f59e0b]/10 text-[#f59e0b] border border-[#f59e0b]/20";
  return "bg-primary/10 text-primary border border-primary/20";
};

// ─── PDF download — no modal, instant ─────────────────────────────────────
async function downloadComplaintPDF(
  complaintText: string,
  harassmentType: string,
  ud: Partial<UserDetails>
) {
  if (!complaintText.trim()) { toast.error("No complaint text to export."); return; }
  try {
    const { jsPDF } = await import("jspdf");
    const doc = new jsPDF({ unit: "mm", format: "a4" });
    const today = fmtDate(new Date().toISOString());
    const docId = `SHA-${Date.now()}`;

    // Header bar
    doc.setFillColor(24, 0, 101); doc.rect(0, 0, 210, 28, "F");
    doc.setTextColor(255, 255, 255);
    doc.setFontSize(13); doc.setFont("courier", "bold");
    doc.text("SAVEHER AI — OFFICIAL COMPLAINT DOCUMENT", 105, 11, { align: "center" });
    doc.setFontSize(8); doc.setFont("courier", "normal");
    doc.text("Generated by SaveHer AI Safety Platform | cybercrime.gov.in", 105, 18, { align: "center" });
    doc.text(`Document ID: ${docId}  |  Date: ${today}`, 105, 24, { align: "center" });

    // Complainant box
    if (ud?.fullName) {
      doc.setFillColor(240, 238, 255); doc.rect(15, 32, 180, 30, "F");
      doc.setTextColor(24, 0, 101);
      doc.setFontSize(9); doc.setFont("courier", "bold");
      doc.text("COMPLAINANT DETAILS", 20, 39);
      doc.setFont("courier", "normal"); doc.setFontSize(8.5);
      doc.text(`Name: ${ud.fullName}`, 20, 46);
      if (ud.phone) doc.text(`Phone: ${ud.phone}`, 110, 46);
      if (ud.email) doc.text(`Email: ${ud.email}`, 20, 51);
      const loc = [ud.city, ud.state].filter(Boolean).join(", ");
      if (loc) doc.text(`Location: ${loc}`, 110, 51);
      doc.text(`Date: ${today}`, 20, 57);
    }

    // Divider
    const bodyStartY = ud?.fullName ? 68 : 34;
    doc.setDrawColor(200, 195, 230); doc.line(15, bodyStartY - 3, 195, bodyStartY - 3);

    // Body text
    doc.setTextColor(0, 0, 0); doc.setFont("courier", "normal"); doc.setFontSize(9.5);
    const lines = doc.splitTextToSize(complaintText, 175);
    let y = bodyStartY;
    for (const line of lines) {
      if (y > 270) {
        // add footer before new page
        doc.setFontSize(7.5); doc.setTextColor(120, 120, 120);
        doc.text("National Cyber Crime Helpline: 1930 (24x7, Free)  |  cybercrime.gov.in", 105, 285, { align: "center" });
        doc.addPage(); y = 18;
        doc.setFontSize(9.5); doc.setTextColor(0, 0, 0); doc.setFont("courier", "normal");
      }
      doc.text(line, 15, y); y += 5.5;
    }

    // Footer on every page
    const pages = doc.getNumberOfPages();
    for (let i = 1; i <= pages; i++) {
      doc.setPage(i);
      doc.setFillColor(24, 0, 101); doc.rect(0, 280, 210, 18, "F");
      doc.setTextColor(255, 255, 255); doc.setFontSize(7.5); doc.setFont("courier", "normal");
      doc.text("National Cyber Crime Helpline: 1930 (24x7, Free)  |  cybercrime.gov.in", 105, 287, { align: "center" });
      doc.text(`SaveHer AI  |  ${docId}  |  Page ${i} of ${pages}`, 105, 293, { align: "center" });
    }

    const filename = `SaveHerAI_Complaint_${harassmentType.replace(/\s+/g, "_")}_${Date.now()}.pdf`;
    doc.save(filename);
    toast.success("PDF downloaded! Submit at nearest Cyber Crime Cell or cybercrime.gov.in", { duration: 7000 });
  } catch (err) {
    console.error("[PDF]", err);
    toast.error("PDF generation failed. Please try again.");
  }
}

// ─── How-To Guide ─────────────────────────────────────────────────────────────
function HowToGuide({
  onCopyOnline,
  onDownloadPDF,
  city,
}: {
  onCopyOnline: () => void;
  onDownloadPDF: () => void;
  city: string;
}) {
  const [tab, setTab] = useState<GuideTab>("online");

  const onlineSteps = [
    {
      icon: "language", title: "Visit cybercrime.gov.in",
      desc: "Open cybercrime.gov.in on your browser. Click \"File a Complaint\" on the homepage.",
      btn: { label: "Open Portal →", action: () => window.open("https://cybercrime.gov.in", "_blank") },
    },
    {
      icon: "list", title: "Choose complaint category",
      desc: "Select \"Women/Child Related Crime\" → \"Cyber Bullying / Stalking / Sexting\" or the relevant category matching your case.",
    },
    {
      icon: "person", title: "Fill your details",
      desc: "Enter your personal details. Use the \"Online Portal Version\" tab above — copy each section into the matching form field.",
      btn: { label: "Copy Online Version →", action: onCopyOnline },
    },
    {
      icon: "upload", title: "Upload evidence",
      desc: "Upload the screenshot(s) you analyzed. Also download and attach the PDF complaint from SaveHer AI as additional evidence.",
      btn: { label: "Download PDF →", action: onDownloadPDF },
    },
    {
      icon: "task_alt", title: "Submit & note complaint ID",
      desc: "Click Submit. You'll receive a Complaint ID — save it! Use it to track your complaint status.",
      btn: { label: "Track Status →", action: () => window.open("https://cybercrime.gov.in/Webform/chkackstatus.aspx", "_blank") },
    },
    {
      icon: "shield", title: "You're done!",
      desc: "Authorities will contact you within 2–7 business days. For urgent help call 1930 (24×7 free helpline).",
      btn: { label: "Call 1930", action: () => window.open("tel:1930") },
    },
  ];

  const offlineSteps = [
    {
      icon: "download", title: "Download the FIR complaint PDF",
      desc: "Click \"Download PDF\" above to get your print-ready FIR complaint document.",
      btn: { label: "Download PDF →", action: onDownloadPDF },
    },
    {
      icon: "location_on", title: "Visit nearest Cyber Crime Cell",
      desc: `Go to your nearest Cyber Crime Police Station or any police station. ${city ? `In ${city}, the Cyber Crime Cell is usually at the main SP / Commissioner office.` : "The Cyber Crime Cell is usually at the main SP / Commissioner office."}`,
    },
    {
      icon: "description", title: "Submit the complaint",
      desc: "Give the printed complaint to the duty officer. Request them to register an FIR under IT Act 2000 and BNS 2023 sections as mentioned in the complaint document.",
    },
    {
      icon: "receipt", title: "Get FIR acknowledgement",
      desc: "Insist on a signed, stamped copy of the FIR. Note the FIR number — this is your legal proof that the complaint was filed.",
    },
    {
      icon: "schedule", title: "Follow up",
      desc: "Follow up every 7 days. If police refuse to file FIR, you can approach the Judicial Magistrate directly under Section 156(3) CrPC.",
    },
  ];

  const steps = tab === "online" ? onlineSteps : offlineSteps;

  return (
    <div className="bg-surface-container-low rounded-xl border border-outline-variant/10 overflow-hidden">
      {/* Emergency banner */}
      <div className="bg-[#7f1d1d] px-6 py-4 flex flex-col sm:flex-row items-start sm:items-center justify-between gap-3">
        <p className="text-white font-semibold text-sm">
          🚨 Need immediate help? Call <span className="font-extrabold">1930</span> — National Cyber Crime Helpline (Free, 24×7)
        </p>
        <a href="tel:1930" className="shrink-0 px-5 py-2 bg-white text-[#7f1d1d] font-extrabold text-sm rounded-lg active:scale-95 duration-200 hover:bg-red-100 transition-colors">
          Call Now
        </a>
      </div>

      <div className="p-6 sm:p-8">
        <h3 className="text-xl font-extrabold text-white mb-6">How to File This Complaint</h3>

        {/* Tab switcher */}
        <div className="flex gap-2 bg-surface-container-high p-1 rounded-xl mb-8 max-w-sm">
          {(["online", "offline"] as GuideTab[]).map((t) => (
            <button key={t} onClick={() => setTab(t)}
              className={`flex-1 py-2.5 rounded-lg text-sm font-bold transition-all ${tab === t ? "bg-primary text-white shadow" : "text-white/50 hover:text-white"}`}>
              {t === "online" ? "🌐 Online (cybercrime.gov.in)" : "🏛️ Offline (Police Station)"}
            </button>
          ))}
        </div>

        {/* Steps */}
        <div className="relative">
          {/* Vertical connector line */}
          <div className="absolute left-5 top-10 bottom-10 w-0.5 bg-white/5" />

          <div className="space-y-6">
            {steps.map((step, i) => (
              <div key={i} className="relative flex gap-5">
                {/* Step number circle */}
                <div className="relative flex flex-col items-center shrink-0">
                  <div className="w-10 h-10 rounded-full bg-primary/20 border border-primary/30 flex items-center justify-center z-10">
                    <span className="text-primary font-extrabold text-sm">{i + 1}</span>
                  </div>
                </div>

                {/* Content */}
                <div className="flex-1 pb-2">
                  <div className="flex items-center gap-2 mb-2">
                    <span className="material-symbols-outlined text-primary text-lg">{step.icon}</span>
                    <h4 className="text-white font-semibold text-sm">{step.title}</h4>
                  </div>
                  <p className="text-white/50 text-sm leading-relaxed mb-3">{step.desc}</p>
                  {step.btn && (
                    <button onClick={step.btn.action}
                      className="inline-flex items-center gap-1.5 px-4 py-2 bg-primary/10 border border-primary/20 text-primary text-xs font-bold rounded-lg hover:bg-primary/20 transition-colors active:scale-95 duration-150">
                      {step.btn.label}
                    </button>
                  )}
                </div>
              </div>
            ))}
          </div>
        </div>
      </div>
    </div>
  );
}

// ═════════════════════════ Main Page ══════════════════════════════════════════
export default function Page() {
  const { user } = useAuth();

  const [fullComplaint, setFullComplaint]   = useState<string>("");
  const [shortComplaint, setShortComplaint] = useState<string>("");
  const [applicableLaws, setApplicableLaws] = useState<ApplicableLaw[]>([]);
  const [activeTab, setActiveTab]           = useState<Tab>("full");
  const [showNextSteps, setShowNextSteps]   = useState(false);
  const [copied, setCopied]                 = useState(false);
  const [harassmentType, setHarassmentType] = useState("Harassment");
  const [savedUD, setSavedUD]               = useState<Partial<UserDetails>>({});

  useEffect(() => {
    try {
      const full  = sessionStorage.getItem("saveher_complaint");
      const short = sessionStorage.getItem("saveher_short_complaint");
      const laws  = sessionStorage.getItem("saveher_applicable_laws");
      const ht    = sessionStorage.getItem("saveher_harassment_type");
      const ud    = sessionStorage.getItem("saveher_user_details");
      if (full)  setFullComplaint(full);
      if (short) setShortComplaint(short);
      if (laws)  setApplicableLaws(JSON.parse(laws));
      if (ht)    setHarassmentType(ht);
      if (ud)    setSavedUD(JSON.parse(ud));
    } catch { /* ignore */ }
  }, []);

  const activeComplaintText = activeTab === "full" ? fullComplaint : shortComplaint;

  // ── Copy
  const handleCopy = () => {
    if (!activeComplaintText) { toast.error("No complaint text to copy."); return; }
    navigator.clipboard.writeText(activeComplaintText)
      .then(() => { setCopied(true); toast.success("Copied!"); setTimeout(() => setCopied(false), 3000); })
      .catch(() => toast.error("Copy failed — please select text manually."));
  };

  const handleCopyOnlineVersion = () => {
    if (!shortComplaint) { toast.error("Portal version not available."); return; }
    navigator.clipboard.writeText(shortComplaint)
      .then(() => toast.success("Online portal version copied!"))
      .catch(() => toast.error("Copy failed."));
  };

  // ── PDF (instant, no modal)
  const handleDownloadPDF = () => {
    downloadComplaintPDF(activeComplaintText, harassmentType, savedUD);
    setShowNextSteps(true);
  };

  const handleOpenPortal = () => window.open("https://cybercrime.gov.in", "_blank");

  return (
    <>
      <header className="fixed top-0 w-full z-50 bg-[#0a0a0f]/60 backdrop-blur-3xl shadow-[0_0_40px_rgba(199,191,255,0.06)]">
        <div className="flex justify-between items-center px-8 py-4 max-w-7xl mx-auto">
          <div className="text-xl font-extrabold tracking-tighter text-white">SaveHer AI</div>
          <nav className="hidden md:flex gap-8 font-semibold text-sm tracking-tight">
            <Link className="text-white/60 hover:text-white transition-colors" href="/">Features</Link>
            <Link className="text-white/60 hover:text-white transition-colors" href="/how-it-works">How it works</Link>
            <Link className="text-white border-b-2 border-[#7c6af7] pb-1 hover:text-white transition-colors" href="/complaint">Report</Link>
          </nav>
          <Link href="/upload"><button className="bg-[#7c6af7] text-white px-6 py-2.5 rounded-lg font-bold text-sm active:scale-95 duration-200">Get Protected</button></Link>
        </div>
      </header>

      <main className="pt-32 pb-20 px-6 max-w-5xl mx-auto min-h-screen flex flex-col gap-8">

        {/* Page header */}
        <div className="mb-2">
          <div className="flex items-center gap-3 mb-4">
            <div className="h-2 w-2 rounded-full bg-primary shadow-[0_0_8px_#c7bfff]" />
            <span className="text-xs font-semibold uppercase tracking-widest text-white/40">Legal Protection Module</span>
          </div>
          <h1 className="text-4xl md:text-5xl font-extrabold tracking-tighter mb-4 text-white">Generated Complaint</h1>
          <p className="text-white/60 text-lg max-w-2xl">Your AI-assisted legal documentation is ready. Review, download, or file online.</p>
        </div>

        {/* Helpline banner */}
        <div className="rounded-xl border border-red-900/40 bg-gradient-to-r from-[#1a0808] to-[#1c0a0a] p-5 flex flex-col sm:flex-row items-start sm:items-center gap-4">
          <div className="flex items-center gap-3 flex-1">
            <div className="w-10 h-10 rounded-full bg-red-900/40 flex items-center justify-center shrink-0">
              <span className="material-symbols-outlined text-red-400" style={{ fontVariationSettings:"'FILL' 1" }}>emergency</span>
            </div>
            <div>
              <p className="text-white font-extrabold text-sm tracking-tight">🚨 National Cyber Crime Helpline</p>
              <p className="text-red-300 text-xs mt-0.5">Call <span className="font-bold">1930</span> &mdash; Free 24×7 Helpline &nbsp;|&nbsp; File online at <span className="font-bold">cybercrime.gov.in</span></p>
            </div>
          </div>
          <div className="flex items-center gap-3 shrink-0">
            <a href="tel:1930" className="flex items-center gap-1.5 px-5 py-2.5 bg-red-700 hover:bg-red-600 text-white font-extrabold text-sm rounded-lg active:scale-95 duration-200 transition-colors">
              <span className="material-symbols-outlined text-sm" style={{ fontVariationSettings:"'FILL' 1" }}>call</span>Call 1930
            </a>
            <button onClick={handleOpenPortal} className="flex items-center gap-1.5 px-5 py-2.5 border border-red-800/50 text-red-300 hover:text-white hover:border-red-600 font-semibold text-sm rounded-lg active:scale-95 duration-200 transition-colors">
              <span className="material-symbols-outlined text-sm">open_in_new</span>Open Portal
            </button>
          </div>
        </div>

        {/* Applicable Laws */}
        {applicableLaws.length > 0 && (
          <div className="bg-surface-container-low rounded-xl p-6 border border-outline-variant/10">
            <h3 className="text-xs font-bold text-on-surface-variant/40 uppercase tracking-widest mb-4">Applicable Laws Identified</h3>
            <div className="flex flex-wrap gap-2">
              {applicableLaws.map((law, i) => (
                <span key={i} className={`text-xs font-semibold px-3 py-1.5 rounded-full ${LAW_SEVERITY_STYLE(law.act + (law.section ?? ""))}`}>
                  {law.section} — {law.act}
                </span>
              ))}
            </div>
          </div>
        )}

        {/* Tab switcher */}
        <div className="flex gap-2 bg-surface-container-high p-1 rounded-xl max-w-md">
          {(["full", "short"] as Tab[]).map((t) => (
            <button key={t} onClick={() => setActiveTab(t)}
              className={`flex-1 py-2.5 rounded-lg text-sm font-bold transition-all ${activeTab === t ? "bg-primary text-white shadow" : "text-white/50 hover:text-white"}`}>
              {t === "full" ? "🏛️ FIR / Police Station" : "🌐 Online Portal Version"}
            </button>
          ))}
        </div>

        {/* Complaint document */}
        <div className="relative group">
          <div className="absolute -inset-1 bg-gradient-to-r from-primary/10 to-transparent blur-2xl opacity-50" />
          <div className="relative bg-surface-container-low rounded-xl border border-outline-variant/10 shadow-2xl overflow-hidden flex flex-col h-[600px]">
            <div className="px-8 py-6 border-b border-outline-variant/15 flex justify-between items-center bg-surface-container-high/30">
              <div className="flex flex-col">
                <span className="text-[10px] font-bold text-primary uppercase tracking-[0.2em]">Document ID: SHA-2026-X99</span>
                <h2 className="font-semibold text-white">
                  {activeTab === "full" ? "OFFICIAL FIR COMPLAINT — Cyber Crime Police Station" : "ONLINE PORTAL VERSION — cybercrime.gov.in"}
                </h2>
              </div>
              <div className="flex gap-2">
                <div className="px-3 py-1 bg-surface-container-highest rounded-full text-[10px] font-bold text-white/60 uppercase">Draft v2.0</div>
                <div className="px-3 py-1 bg-primary/10 rounded-full text-[10px] font-bold text-primary uppercase">Ready for Filing</div>
              </div>
            </div>
            <div className="flex-1 overflow-y-auto p-12 text-white/80 leading-relaxed">
              <div className="max-w-3xl mx-auto space-y-8">
                <div className="text-sm font-bold uppercase tracking-widest text-white/40 border-b border-outline-variant/10 pb-4 mb-8">
                  Internal Legal Counsel &amp; Reporting Division
                </div>
                {activeComplaintText ? (
                  <div className="text-sm leading-relaxed whitespace-pre-wrap text-white/80">{activeComplaintText}</div>
                ) : (
                  <section>
                    <h3 className="text-white font-bold mb-4">I. PRELIMINARY STATEMENT</h3>
                    <p className="text-sm">No complaint loaded. Please go to <Link href="/upload" className="text-primary underline">Upload</Link>, analyze a screenshot, and click &quot;Generate Complaint&quot; on the result page.</p>
                  </section>
                )}
                <div className="pt-12 mt-12 border-t border-outline-variant/10 space-y-2 text-center">
                  <p className="text-[10px] text-white/30 uppercase tracking-widest">For immediate assistance: Call 1930 (National Cyber Crime Helpline) or visit cybercrime.gov.in</p>
                  <p className="text-[10px] text-white/20 uppercase tracking-widest">End of Generated Document — SaveHer AI Sentinel System</p>
                </div>
              </div>
            </div>
          </div>
        </div>

        {/* Action buttons */}
        <div className="flex flex-col md:flex-row items-center justify-between gap-6">
          <div className="flex flex-wrap items-center gap-4">
            <button onClick={handleCopy} disabled={!activeComplaintText}
              className="flex items-center gap-2 bg-gradient-to-br from-primary to-primary-container text-on-primary font-extrabold px-8 py-4 rounded-lg shadow-lg hover:shadow-primary/20 transition-all active:scale-95 disabled:opacity-50 disabled:cursor-not-allowed">
              <span className="material-symbols-outlined text-xl">{copied ? "check" : "content_copy"}</span>
              <span>{copied ? "Copied!" : `Copy ${activeTab === "full" ? "FIR Version" : "Portal Version"}`}</span>
            </button>

            <button onClick={handleDownloadPDF} disabled={!activeComplaintText}
              className="flex items-center gap-2 border border-outline-variant/20 bg-transparent text-white/60 font-semibold px-8 py-4 rounded-lg hover:bg-white/5 hover:text-white transition-all active:scale-95 disabled:opacity-50 disabled:cursor-not-allowed">
              <span className="material-symbols-outlined text-xl">download</span>
              <span>Download PDF</span>
            </button>

            <button onClick={handleOpenPortal}
              className="flex items-center gap-2 border border-primary/30 bg-primary/5 text-primary font-semibold px-8 py-4 rounded-lg hover:bg-primary/10 transition-all active:scale-95">
              <span className="material-symbols-outlined text-xl">open_in_new</span>
              <span>Open cybercrime.gov.in</span>
            </button>
          </div>
          <div className="flex items-center gap-2 text-white/40 text-xs font-semibold tracking-wide">
            <span className="material-symbols-outlined text-sm" style={{ fontVariationSettings:"'FILL' 1" }}>verified_user</span>
            DOCUMENT ENCRYPTED VIA AES-256
          </div>
        </div>

        {/* Next steps card */}
        {showNextSteps && (
          <div className="bg-gradient-to-br from-primary-container/20 to-surface-container-low rounded-xl p-8 border border-primary/20">
            <div className="flex items-center gap-3 mb-4">
              <span className="material-symbols-outlined text-primary text-2xl" style={{ fontVariationSettings:"'FILL' 1" }}>task_alt</span>
              <h3 className="text-xl font-extrabold text-white">PDF Downloaded — Next Steps</h3>
            </div>
            <div className="space-y-3">
              {[
                "Visit cybercrime.gov.in and file online using the Portal Version above",
                "OR take the downloaded PDF to your nearest Cyber Crime Cell / police station",
                "Keep this document safe as legal evidence — do not share with the accused",
              ].map((step, i) => (
                <div key={i} className="flex items-start gap-3 px-4 py-3 bg-surface-container-highest rounded-lg">
                  <span className="text-primary font-extrabold text-sm shrink-0 mt-0.5">{i + 1}.</span>
                  <span className="text-sm text-white/80">{step}</span>
                </div>
              ))}
            </div>
            <button onClick={handleOpenPortal} className="mt-6 flex items-center gap-2 bg-primary/10 border border-primary/30 text-primary font-semibold px-6 py-3 rounded-lg hover:bg-primary/20 transition-all active:scale-95 text-sm">
              <span className="material-symbols-outlined text-lg">open_in_new</span>File Online Now
            </button>
          </div>
        )}

        {/* ── How to File Guide ── */}
        <HowToGuide
          onCopyOnline={handleCopyOnlineVersion}
          onDownloadPDF={handleDownloadPDF}
          city={savedUD?.city ?? ""}
        />

      </main>

      {/* Copied pill */}
      {copied && (
        <div className="fixed bottom-12 left-1/2 -translate-x-1/2 z-[100] animate-in fade-in slide-in-from-bottom-4 duration-500">
          <div className="bg-surface-container-highest/90 backdrop-blur-xl border border-primary/20 px-6 py-3 rounded-full flex items-center gap-3 shadow-2xl">
            <div className="bg-primary/20 p-1 rounded-full">
              <span className="material-symbols-outlined text-primary text-sm" style={{ fontVariationSettings:"'FILL' 1" }}>check_circle</span>
            </div>
            <span className="text-sm font-bold tracking-tight text-white">Copied!</span>
            <div className="w-px h-4 bg-outline-variant/30 ml-2" />
            <span className="text-[10px] uppercase font-bold text-white/40 tracking-widest">Ready to paste</span>
          </div>
        </div>
      )}

      <footer className="w-full border-t border-white/5 bg-[#0a0a0f]">
        <div className="flex flex-col md:flex-row justify-between items-center px-12 py-10 w-full max-w-7xl mx-auto">
          <div className="text-lg font-black text-white/80 mb-6 md:mb-0">SaveHer AI</div>
          <div className="flex flex-wrap justify-center gap-8 mb-6 md:mb-0">
            <Link className="text-white/40 text-xs font-normal uppercase tracking-widest hover:text-white transition-colors" href="/">Privacy Policy</Link>
            <Link className="text-white/40 text-xs font-normal uppercase tracking-widest hover:text-white transition-colors" href="/">Terms of Service</Link>
            <Link className="text-white/40 text-xs font-normal uppercase tracking-widest hover:text-white transition-colors" href="/">Contact Support</Link>
            <Link className="text-white/40 text-xs font-normal uppercase tracking-widest hover:text-white transition-colors" href="/sos">Emergency Protocol</Link>
          </div>
          <div className="text-white/40 text-[10px] uppercase tracking-[0.2em]">© 2026 SaveHer AI. Protected by The Sentinel&apos;s Veil.</div>
        </div>
      </footer>
    </>
  );
}
